Strings
Korrumz2PL/skyndalex-public pull request #17
Opened 2021-11-04 21:36 UTC by ThatRemixiak

2021-11-04 21:45 UTC, rkubapl requested changes
Nie lepiej nazwę użytkownika czytać z ID niż z pliku?

2021-11-05 06:23 UTC, ThatRemixiak commented
Poprawilem to

2021-11-05 06:23 UTC, ThatRemixiak commented
ale jeszcxe wiecej bedzie

2021-11-05 07:34 UTC, rkubapl commented
no i gituwa

2021-11-06 13:13 UTC, Korrumz2PL reviewed
Jeszcze się nad tym zastanawiam.

2021-11-24 18:20 UTC, Korrumz2PL reviewed
Dodane. Zamykam pull request, bo tu są stare komendy.

2021-11-24 18:21 UTC, closed without merging